/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.DibujoArbol;

/**
 *
 * @author josue
 */
public class Menu extends javax.swing.JFrame {
        
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /** 
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        //inicializar graficador pasando el arbol
        graficador = new DibujoArbol(miArbol);
        //ajustar tamaño al panel
        graficador.setSize(pnlContenedor.getSize());
        //agregar al panel
        pnlContenedor.add(graficador);
    }   
    
    //metodo para actualizar el dibujo del arbol
    private void actualizarGrafico() {
    //limpia el dibujo viejo y llama a paintComponent de nuevo
    graficador.repaint(); 
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnInsertar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Eliminar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdBorrar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        txtErrores = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Eliminar1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdBuscar = new javax.swing.JTextField();
        btnBorrar1 = new javax.swing.JButton();
        lblResultadoId = new javax.swing.JLabel();
        lblResultadoCat = new javax.swing.JLabel();
        lblResultadoDesc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Eliminar2 = new javax.swing.JLabel();
        btnPreOrden = new javax.swing.JButton();
        btnInOrden = new javax.swing.JButton();
        btnPostOrden = new javax.swing.JButton();
        btnContarEspeciales = new javax.swing.JButton();
        btnListarFrasesHojas = new javax.swing.JButton();
        btnConsultasAdicionales = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaConsola = new javax.swing.JTextArea();
        pnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("Fondo"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setName("pnlnsertar"); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Insertar");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID:");

        txtId.setBackground(new java.awt.Color(153, 153, 153));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setName("txtId"); // NOI18N

        txtDescripcion.setBackground(new java.awt.Color(153, 153, 153));
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setName("txtDescripcion"); // NOI18N

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripcion:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Categoria:");

        cmbCategoria.setBackground(new java.awt.Color(153, 153, 153));
        cmbCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civiles", "Equipo", "Súper héroes", "Objetos", "Súper villanos", "Paneles", "Cara a cara", "Frases icónicas", "Película especial" }));
        cmbCategoria.setName("cmbCategoria"); // NOI18N

        btnInsertar.setBackground(new java.awt.Color(153, 153, 153));
        btnInsertar.setForeground(new java.awt.Color(0, 0, 0));
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion)
                    .addComponent(txtId)
                    .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(btnInsertar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnInsertar)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setName("pnlnsertar"); // NOI18N

        Eliminar.setForeground(new java.awt.Color(0, 0, 0));
        Eliminar.setText("Eliminar");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID:");

        txtIdBorrar.setBackground(new java.awt.Color(153, 153, 153));
        txtIdBorrar.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBorrar.setName("txtId"); // NOI18N

        btnEliminar.setBackground(new java.awt.Color(153, 153, 153));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Borrar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtErrores.setEditable(false);
        txtErrores.setBackground(new java.awt.Color(153, 153, 153));
        txtErrores.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdBorrar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eliminar)
                            .addComponent(jLabel6)
                            .addComponent(btnEliminar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtErrores))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(txtErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setName("pnlnsertar"); // NOI18N

        Eliminar1.setForeground(new java.awt.Color(0, 0, 0));
        Eliminar1.setText("Buscar");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID:");

        txtIdBuscar.setBackground(new java.awt.Color(153, 153, 153));
        txtIdBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtIdBuscar.setName("txtId"); // NOI18N

        btnBorrar1.setBackground(new java.awt.Color(153, 153, 153));
        btnBorrar1.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar1.setText("Buscar");
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });

        lblResultadoId.setForeground(new java.awt.Color(0, 0, 0));
        lblResultadoId.setText("ID:");

        lblResultadoCat.setForeground(new java.awt.Color(0, 0, 0));
        lblResultadoCat.setText("Categoria:");

        lblResultadoDesc.setForeground(new java.awt.Color(0, 0, 0));
        lblResultadoDesc.setText("Descripcion:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Eliminar1)
                    .addComponent(jLabel7)
                    .addComponent(btnBorrar1)
                    .addComponent(lblResultadoId)
                    .addComponent(lblResultadoCat)
                    .addComponent(lblResultadoDesc)
                    .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eliminar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultadoId)
                .addGap(4, 4, 4)
                .addComponent(lblResultadoDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultadoCat)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setName("pnlnsertar"); // NOI18N

        Eliminar2.setForeground(new java.awt.Color(0, 0, 0));
        Eliminar2.setText("Consultas extra");

        btnPreOrden.setBackground(new java.awt.Color(153, 153, 153));
        btnPreOrden.setForeground(new java.awt.Color(0, 0, 0));
        btnPreOrden.setText("Pre Orden");
        btnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrdenActionPerformed(evt);
            }
        });

        btnInOrden.setBackground(new java.awt.Color(153, 153, 153));
        btnInOrden.setForeground(new java.awt.Color(0, 0, 0));
        btnInOrden.setText("In Orden");
        btnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrdenActionPerformed(evt);
            }
        });

        btnPostOrden.setBackground(new java.awt.Color(153, 153, 153));
        btnPostOrden.setForeground(new java.awt.Color(0, 0, 0));
        btnPostOrden.setText("Post Orden");
        btnPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrdenActionPerformed(evt);
            }
        });

        btnContarEspeciales.setBackground(new java.awt.Color(153, 153, 153));
        btnContarEspeciales.setForeground(new java.awt.Color(0, 0, 0));
        btnContarEspeciales.setText("Especiales");
        btnContarEspeciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarEspecialesActionPerformed(evt);
            }
        });

        btnListarFrasesHojas.setBackground(new java.awt.Color(153, 153, 153));
        btnListarFrasesHojas.setForeground(new java.awt.Color(0, 0, 0));
        btnListarFrasesHojas.setText("Frases");
        btnListarFrasesHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFrasesHojasActionPerformed(evt);
            }
        });

        btnConsultasAdicionales.setBackground(new java.awt.Color(153, 153, 153));
        btnConsultasAdicionales.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultasAdicionales.setText("Adicionales");
        btnConsultasAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasAdicionalesActionPerformed(evt);
            }
        });

        txtAreaConsola.setBackground(new java.awt.Color(102, 102, 102));
        txtAreaConsola.setColumns(20);
        txtAreaConsola.setRows(5);
        jScrollPane1.setViewportView(txtAreaConsola);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eliminar2)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnPreOrden)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInOrden)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPostOrden)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnContarEspeciales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnListarFrasesHojas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultasAdicionales)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eliminar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreOrden)
                    .addComponent(btnInOrden)
                    .addComponent(btnPostOrden)
                    .addComponent(btnContarEspeciales)
                    .addComponent(btnListarFrasesHojas)
                    .addComponent(btnConsultasAdicionales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pnlContenedor.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 582, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //logica 
    
    //gestor de logica
    Logica.ArbolABB miArbol = new Logica.ArbolABB();
    
    //gestor para dibujar el arbol
    Logica.DibujoArbol graficador;
    
    
    //insertar cartas
    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
            // Validaciones de campos obligatorios [cite: 171, 172]
            if (txtId.getText().trim().isEmpty() || txtDescripcion.getText().trim().isEmpty()) {
                throw new Exception("Todos los campos (Id, Descripción y Categoría) son obligatorios.");
            }

            int id = Integer.parseInt(txtId.getText().trim());
            String descripcion = txtDescripcion.getText().trim();
            String categoria = cmbCategoria.getSelectedItem().toString();

            // Llamada a la lógica (esta ya valida ID positivo y duplicados) [cite: 173, 174]
            miArbol.insertar(new Entidades.Tarjeta(id, descripcion, categoria));

            // Limpiar campos tras éxito (No se usan cuadros de diálogo para éxito) [cite: 50, 168]
            txtId.setText("");
            txtDescripcion.setText("");
            System.out.println("Insertado correctamente"); 
            
            //actualizar arbol
            actualizarGrafico();

        } catch (NumberFormatException e) {
            // Los cuadros de diálogo solo se permiten para errores o excepciones [cite: 49, 170]
            javax.swing.JOptionPane.showMessageDialog(this, "El ID debe ser un número entero positivo.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    //eliminar cartas
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            txtErrores.setText(""); // Limpiar mensajes previos
            int id = Integer.parseInt(txtIdBorrar.getText().trim());

            miArbol.eliminar(id);
            txtIdBorrar.setText("");
            //actualizar arbol
            actualizarGrafico();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un ID válido para eliminar.");
        } catch (Exception e) {
            // Mostrar la razón específica en el área de texto 
            txtErrores.setText(e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    //buscar
    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        try {
            int id = Integer.parseInt(txtIdBuscar.getText().trim());
            Entidades.Tarjeta encontrada = miArbol.buscar(id);

            if (encontrada != null) {
                lblResultadoId.setText("ID: " + encontrada.getId());
                lblResultadoDesc.setText("Desc: " + encontrada.getDescripcion());
                lblResultadoCat.setText("Cat: " + encontrada.getCategoria());
            } else {
                // Informar en la interfaz si no existe [cite: 132]
                lblResultadoId.setText("El elemento no fue encontrado.");
                lblResultadoDesc.setText("");
                lblResultadoCat.setText("");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error en la búsqueda.");
        }
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrdenActionPerformed
        // Muestra IDs separados por guiones sin cuadros de diálogo 
        txtAreaConsola.setText("Recorrido Pre-Orden:\n" + miArbol.preOrden());
    }//GEN-LAST:event_btnPreOrdenActionPerformed

    private void btnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrdenActionPerformed
        // Muestra IDs separados por guiones sin cuadros de diálogo
        txtAreaConsola.setText("Recorrido In-Orden:\n" + miArbol.inOrden());
    }//GEN-LAST:event_btnInOrdenActionPerformed

    private void btnPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrdenActionPerformed
        // Muestra IDs separados por guiones sin cuadros de diálogo
        txtAreaConsola.setText("Recorrido Post-Orden:\n" + miArbol.postOrden());
    }//GEN-LAST:event_btnPostOrdenActionPerformed

    private void btnContarEspecialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarEspecialesActionPerformed
        // Calcula total de "Súper héroes" o "Súper villanos"
        int total = miArbol.contarHeroesVillanos();
        txtAreaConsola.setText("Cantidad de Súper héroes o Súper villanos: " + total);
    }//GEN-LAST:event_btnContarEspecialesActionPerformed

    private void btnListarFrasesHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFrasesHojasActionPerformed
        // Lista descripciones de categoría "Frases icónicas" que sean hojas 
        String lista = miArbol.listarFrasesIconicasHojas();
        if (lista.isEmpty()) {
            txtAreaConsola.setText("No se encontraron frases icónicas en nodos hoja.");
        } else {
            txtAreaConsola.setText("Frases icónicas (Nodos Hoja):\n" + lista);
        }
    }//GEN-LAST:event_btnListarFrasesHojasActionPerformed

    private void btnConsultasAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasAdicionalesActionPerformed
        try {
        // Esta opción consolida los puntos (a), (b) y (c) del enunciado [cite: 153, 154, 155]
        StringBuilder sb = new StringBuilder();
        sb.append("=== CONSULTAS ADICIONALES DEL ÁRBOL ===\n\n");
        
        // (a) Total Súper héroes/villanos [cite: 153]
        sb.append("a) Total Súper héroes o Súper villanos: ").append(miArbol.contarHeroesVillanos()).append("\n\n");
        
        // (b) Lista de Frases icónicas en hojas [cite: 154]
        sb.append("b) Frases icónicas en nodos hoja:\n");
        String frases = miArbol.listarFrasesIconicasHojas();
        sb.append(frases.isEmpty() ? "Ninguna encontrada.\n" : frases).append("\n");
        
        // (c) Mayor y Menor Id [cite: 155, 156]
        // Se obtienen mediante recorrido del árbol [cite: 158]
        sb.append("c) Rango de IDs en el sistema:\n");
        sb.append("   - ID Menor: ").append(miArbol.obtenerMenor()).append("\n");
        sb.append("   - ID Mayor: ").append(miArbol.obtenerMayor()).append("\n");
        
        txtAreaConsola.setText(sb.toString());
        } catch (Exception e) {
            // Solo se permiten cuadros emergentes para excepciones [cite: 49, 170]
            txtAreaConsola.setText("Error al procesar consultas: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConsultasAdicionalesActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Eliminar1;
    private javax.swing.JLabel Eliminar2;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnConsultasAdicionales;
    private javax.swing.JButton btnContarEspeciales;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInOrden;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnListarFrasesHojas;
    private javax.swing.JButton btnPostOrden;
    private javax.swing.JButton btnPreOrden;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultadoCat;
    private javax.swing.JLabel lblResultadoDesc;
    private javax.swing.JLabel lblResultadoId;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JTextArea txtAreaConsola;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtErrores;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdBorrar;
    private javax.swing.JTextField txtIdBuscar;
    // End of variables declaration//GEN-END:variables
}
